// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASPnwhendqN76m-Y3BkGuC-_ieXXwApRM',
    appId: '1:716959775532:web:986875473d4a3839e28a89',
    messagingSenderId: '716959775532',
    projectId: 'resela-association',
    authDomain: 'resela-association.firebaseapp.com',
    databaseURL: 'https://resela-association-default-rtdb.firebaseio.com',
    storageBucket: 'resela-association.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdg2eUAxkY4PLFWrUXyMZFRqeIAKYHBOY',
    appId: '1:716959775532:android:fdbe045e5d526f18e28a89',
    messagingSenderId: '716959775532',
    projectId: 'resela-association',
    databaseURL: 'https://resela-association-default-rtdb.firebaseio.com',
    storageBucket: 'resela-association.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlAaWdoQUAkS-kGlO1FY3WhYs7dnOR5mM',
    appId: '1:716959775532:ios:6346b1e12206f459e28a89',
    messagingSenderId: '716959775532',
    projectId: 'resela-association',
    databaseURL: 'https://resela-association-default-rtdb.firebaseio.com',
    storageBucket: 'resela-association.appspot.com',
    iosClientId: '716959775532-25dtl18sdssnlqhqss6sjultcn4a56dm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ticketApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlAaWdoQUAkS-kGlO1FY3WhYs7dnOR5mM',
    appId: '1:716959775532:ios:9d1532df09a6c38de28a89',
    messagingSenderId: '716959775532',
    projectId: 'resela-association',
    databaseURL: 'https://resela-association-default-rtdb.firebaseio.com',
    storageBucket: 'resela-association.appspot.com',
    iosClientId: '716959775532-98g5osiajd9c4adbj6ds8hp2n0k0uqmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.ticketApp.RunnerTests',
  );
}
